### ISSUE TITLE
Change actas in Toolkits to match Impersonate a user in Kits

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#398] opened 2019-06-17 15:18 UTC
### Description ###
Kits uses the admin group to identify which individuals can access the "Impersonate a user" feature.  The same logic should be applied in Toolkits to be consistent between the two applications.

**Comment by joliet** [comment] 2019-09-25 14:55
Do we still need to do this @ewendland23 ?  If our goal is to move users to Kits and sunset the Toolkits front-end this year, would this still be needed?

**Comment by joliet** [comment] 2019-11-18 13:54
Hi @ewendland23 .  I'm trying to verify this on test but I can't find the "Act As" feature.  I've never used it before.  Is that only available to you?

**Comment by noahhh** [comment] 2019-11-18 13:55
Hi @joliet ,

Old toolkits actas is in https://kits-test.oit.duke.edu/actas

**Comment by joliet** [comment] 2019-11-22 16:28
This doesn't seem to be working as intended.  My testing steps and outcome:

1. Clicked on the link above - https://kits-test.oit.duke.edu/actas
2. Entered two different faculty netids for testing - rodger and seminars.
3. After clicking the Act As button, I am taken to Kits and see a notification that I am acting as the user.
4. I do not see either users kits, just my own.
5. I do not see the persistent message at the bottom of the screen in Kits that reminds me I am impersonating a user with the exit option.
6. The user account in the upper right of the screen shows me.  When I impersonate in Kits, I see the user I am impersonating there.

I get similar results in Toolkits- test, although I've never used this functionality there so I don't know what is expected.  After completing steps 1-3 above this is what happens:

4. I do not see other users toolkits, just my own.
5. I still see the admin options in the top menu.

@ewendland23 and @noahhh , let me know if I missed something and need to re-test.

**Comment by noahhh** [comment] 2019-11-22 16:33
Hi @joliet ,

I'll look in to this.  It all works for me so there is probably somewhere further down the line blocking you for not being a super user.

Thanks,
Noah

**Comment by joliet** [comment] 2019-11-22 16:37
Thanks @noahhh !

**Comment by noahhh** [comment] 2019-12-02 15:40
@joliet Could you try this again when you have a chance?

**Comment by joliet** [comment] 2019-12-03 16:07
Re-tested and this is working.  Closing.

**Closed by joliet** 2019-12-03 16:07 UTC
Labels: enhancement
