### ISSUE TITLE
What happens with cross-listed courses? Is there a master group that's created?

### ISSUE THREAD

**Issue by LASHirsh** [DukeLearningInnovation/kits#74] opened 2018-01-10 21:25 UTC

**Comment by profmikegreene** [comment] 2018-01-16 14:16
I believe users choose which course will serve as master and just add rosters to that @joliet is that correct? Is there more to it technically @ewendland23?

**Comment by joliet** [comment] 2018-02-06 18:36
Sakai doesn't handle this well but Toolkits does.  When a Toolkit is created for one of the cross-listed offerings, the remaining cross-listed courses are automatically added to the group. The main course will likely depend on the faculty member's department, and they will want that to be the course title. I can give some specific examples if this is unclear.  Just let me know.

**Comment by swwalker** [comment] 2018-09-06 14:55
Closed - Duplicate of #205

**Closed by swwalker** 2018-09-06 14:55 UTC
Labels: duplicate, question
