### ISSUE TITLE
Improve error screen for bulk add users to kits

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#416] opened 2019-07-24 14:27 UTC
The error window seen when bulk adding users to Kits needs some improvement with spacing. It would also be better to have a way to close the window instead of it disappearing automatically. Users may need to capture the problematic netids to further investigate, especially Alumni who will be using the bulk add feature often.

![Kits_Bulk_Add_Error](https://user-images.githubusercontent.com/7387760/61801891-8dde5480-adfd-11e9-926f-8ba9ac613a00.png)

**Comment by swwalker** [comment] 2019-07-29 14:09
Duplicate of #412. Closing this issue and keeping #412 open.

**Closed by swwalker** 2019-07-29 14:09 UTC
Labels: enhancement
