### ISSUE TITLE
Managing multiple sections of a course

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#356] opened 2019-01-11 17:22 UTC
I am *instructor* trying to *add a single instance of sakai or other apps to multiple rosters at once* but *can't* because *Kits has a 1:1 relationship between apps and rosters* which makes me feel *annoyed because Kits doesn't fit my mental model for teaching*.

How might we (the Kits project team) allow faculty to manage multiple rosters at once to Kits fits for teaching scenarios than 1 roster = 1 kit = 1 card?

**Comment by swwalker** [comment] 2019-02-12 19:31
duplicate of #133

**Closed by swwalker** 2019-02-12 19:31 UTC
Labels: Definitely, Problem Statement
