### ISSUE TITLE
Timing issue for newly created Kits

### ISSUE THREAD

**Issue by ewendland23** [DukeLearningInnovation/kits#352] opened 2019-01-10 18:40 UTC
If a user logs in and has a course membership for a course not yet in Kits, Kits will create a new course and kick off a process to add the members from Grouper/SISS.  If the user presses the 'Add App' button prior to that membership be completed it will give them a 404 screen.

Example.
This course was created:
I, [2019-01-10T**12:54:55**.202532 #355]  INFO -- : [df928b91-3fff-43b4-be31-9db2d6d9f631] Started GET "/toolkits2/get_kit?urn=GS%3A762%3A01%3A5674%3A1670" for 10.197.28.136 at 2019-01-10 12:54:55 -0500
I, [2019-01-10T12:54:55.203879 #355]  INFO -- : [df928b91-3fff-43b4-be31-9db2d6d9f631] Processing by Toolkits2::DashboardController#get_kit as JSON
I, [2019-01-10T12:54:55.203931 #355]  INFO -- : [df928b91-3fff-43b4-be31-9db2d6d9f631]   Parameters: {"urn"=>"GS:762:01:5674:1670"}

 ===>   created record (times in utc)
#<Course id: 32275, name: "GS 762 - 01: Digital Pedagogy (Lecture)", creator: "1000001375", link_to: "GS:762:01:5674:1670", created_at: "2019-01-10 17:54:54", updated_at: "2019-01-10 17:54:54", community_variety_id: 4>

User accessed it like this:
I, [2019-01-10T**12:55:00**.451849 #355]  INFO -- : [97444e82-c54f-420e-bc96-16ec1b40bc82] Started GET "/toolkits2/app_store/32275" for 10.197.28.136 at 2019-01-10 12:55:00 -0500
I, [2019-01-10T12:55:00.453004 #355]  INFO -- : [97444e82-c54f-420e-bc96-16ec1b40bc82] Processing by Toolkits2::AppStoreController#index as HTML
I, [2019-01-10T12:55:00.453058 #355]  INFO -- : [97444e82-c54f-420e-bc96-16ec1b40bc82]   Parameters: {"id"=>"32275"}
I, [2019-01-10T12:55:00.495468 #355]  INFO -- : [97444e82-c54f-420e-bc96-16ec1b40bc82]   Rendering public/404.html
I, [2019-01-10T12:55:00.496347 #355]  INFO -- : [97444e82-c54f-420e-bc96-16ec1b40bc82]   Rendered public/404.html (0.7ms)

And it worked fine:
I, [2019-01-10T**12:56:02.**379086 #355]  INFO -- : [64fe80af-1bc1-4fa8-b2b7-1bc19e3bfe27] Started GET "/toolkits2/app_store/32275" for 10.197.28.136 at 2019-01-10 12:56:02 -0500

**Comment by noahhh** [comment] 2019-01-30 18:12
This item has been pushed to the kits-test environment.

I am not fully sure how you should test it, but I would suggest you could either:

Have the user who first encountered this issue in prod try to reproduce it in test, assuming they haven't visited test yet to create the courses.
Or use a student/faculty with a course not yet in toolkits.

**Comment by joliet** [comment] 2019-10-25 17:17
Tested this issue on kits-test with faculty Thavolia Glymph.  When I used Act As to masquerade as Thavolia, I had some unexpected results.  She had two kits for courses she is teaching in Fall 2019 - CROSSLISTED COURSE F19 Civil War And Reconstruction (Lecture) and HISTORY 393 - 14 F19
Research Independent Study.  For both of these courses, she is listed as an instructor in DukeHub.

For the CROSSLISTED COURSE F19 Civil War And Reconstruction (Lecture) kit, Thavolia could only see Add App and View Crosslistings.  For the HISTORY 393 - 14 F19 Research Independent Study kit, she could only see Add App and could only add the Custom Link app (as if she had only student access?).  See screenshots.

![History_Crosslist_Instructor_Access](https://user-images.githubusercontent.com/7387760/67590738-d0c80500-f729-11e9-9bdd-b5e6df47a03a.png)
![History_IndStudy_Instructor_View](https://user-images.githubusercontent.com/7387760/67590749-d4f42280-f729-11e9-8533-5e849f5ec16b.png)

**Comment by swwalker** [comment] 2019-10-28 14:12
@joliet - Because this issue is specifically dealing with the ability to add an app to a newly created kit, I have created a new issue that details your findings regarding instructors being unable to access the appropriate functions for a newly created kit (#461).

Does what you found in #461 prevent you from verifying what Noah details regarding app store access?  "If a user logs in and tries to view the app store for a course that is in first time set up, it will display a page with a message letting them know the course is still setting up. At this point, we know they belong in the course, but not their role so we cannot show them the app store. The page refreshes every 5 seconds, and will display the app store when finished."

If the app store issue has been resolved for newly created kits, we can close this one; otherwise, we will leave it open to be tested with the related issue.

**Comment by joliet** [comment] 2019-10-28 19:33
@swwalker Thanks for leaving this open.  I do need to do more testing to try to replicate this issue.  I will try to do that now and report back.

**Comment by joliet** [comment] 2019-10-28 19:44
I just tested this again on kits-test with instructor Stacy Tantum.  When I clicked on the App Store and select one of Stacy's courses from the drop down menu, I see the message "The course you are attempting to view this page for is still being set up. Please wait while we complete the setup. You will be redirected upon completion."  So, no 404 error.  Closing as fixed.

**Closed by joliet** 2019-10-28 19:44 UTC
Labels: Epic: Manage kit apps, bug
