### ISSUE TITLE
Track the origin of Toolkits/Kits being created

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#460] opened 2019-10-25 15:51 UTC
I am Toolkits/Kits administrator trying to understand how Toolkits/Kits is being used but don't have the data I need because there is no method for tracking it.  This makes me feel frustrated and ineffective.

How might we (the Kits project team), develop a way to track in which tool (Toolkits or Kits) a toolkit or kit is being created?

**Questions**
Does (will) toolkits and kits use the same naming convention for courses and user-created toolkits/kits?

**Assumptions**
Being able to track the origin of a toolkit/kit, we can better understand why users choose one tool over another, and address potential gaps/needs in Kits.

**Related Issues**

**Hypotheses**

**Comment by joliet** [comment] 2019-10-25 15:53
Related to implementing issue "Prompt existing Toolkits users to use Kits" https://github.com/DukeLearningInnovation/kits/issues/446

We'll need a way to track who is using each tool to understand user migration for Toolkits to Kits, Kits gaps, and how close we are to sunsetting the old Toolkits UI.

**Comment by swwalker** [comment] 2020-01-06 18:55
Duplicate of #477

**Closed by swwalker** 2020-01-06 18:55 UTC
Labels: Problem Statement
